/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.0.5-286-g0c7dc61052"
#endif /* AVUTIL_FFVERSION_H */
