
#define ERR_ALLOC_OUTPUT_CTX     -1001
#define ERR_MALLOC_MAPPING       -1002
#define ERR_CREATE_NEW_STREAM    -1003
#define ERR_DIMENSIONS_NOT_SET   -1004

#define ERR_COMPOSITE_NO_ENV              -2001
#define ERR_COMPOSITE_NO_OUTPUT_CONTEXT   -2002
#define ERR_COMPOSITE_NO_INPUT_CONTEXT    -2003
#define ERR_COMPOSITE_NO_OUTPUT_STREAM    -2004
#define ERR_COMPOSITE_EXCEED_VIDEO_LIMIT  -2005


